### ISSUE TITLE
Добавить проверку фото при загрузке фото

### ISSUE THREAD

**Issue by kushedow** [skypro-fastdev/hhgate#10]
**Проблема:** 

Сейчас пользователю разрешается загружать любой тип файлов, а ошибка при загрузке файла не показывается в интерфейсе пользователя, ошибка присутствует только в консоли и судя по всему приходит от HH

<img width="607" alt="image" src="https://github.com/user-attachments/assets/6016a74f-45d3-4cc6-9d27-161d75770780">

<img width="607" alt="image" src="https://github.com/user-attachments/assets/87a4c47d-2113-462f-9e74-e9539f574c96">

**Решение:**

Проверять тип (только jpeg/jpg/png) и размер файла при загрузке.
Возвращать сообщение об ошибке одной строкой

**Comment by RedKrane-dev** [comment]
Готово, можно тестировать

**Comment by kushedow** [comment]
Не проверяется размер файла

**Comment by RedKrane-dev** [comment]
Теперь точно готово, можно тестировать
