### ISSUE TITLE
Поменять логику создания работы, если не включена легенда

### ISSUE THREAD

**Issue by kushedow** [skypro-fastdev/hhgate#7]
При отправке поля legend_on== False 

Создается только одна работа. У этой работы должны быть использованы поля:

previous_job_type: "legend",
previous_job_organisation: "",
previous_job_position: "",
previous_job_industry: "",
previous_job_from: "2022-04-16",
previous_job_to: "2024-08-03",
previous_job_experience: "",
previous_job_prompt: "",

Все поля, начинающиеся с recent... – не используются

Для этого в модели нужно добавить поле legend_on и сделать все поля recent...  – опцинальными

**Comment by kushedow** [comment]
Готово, можно тестировать :)

**Comment by RedKrane-dev** [comment]
Поле legend_on добавлено, логика заполнения recent job поправлена. Протестировано
